### ISSUE TITLE
Undocumented Matlab wait option is gone in 2015b

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/spotless-pod#2]
The CMakeLists.txt for spotless-pod calls matlab using
```
COMMAND ${matlab} -wait -nosplash -nodesktop -nodisplay -r "\"cd('${CMAKE_CURRENT_SOURCE_DIR}');spot_pods_install('${CMAKE_INSTALL_PREFIX}/matlab','${relpath}');exit\""
```

The -wait option, which has always been undocumented, seems to not exist at all anymore in 2015b. This results in the following message during build:
```
Unrecognized MATLAB option "wait".
```

I've also been seeing leftover Matlab processes that use 116% CPU accumulating over the course of the day. Here's the call tree for one of those processes:
```
 |-+- 28142 twan /Applications/Xcode.app/Contents/Developer/usr/bin/make install
 | \-+- 28145 twan /Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
 |   \-+- 28149 twan /Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
 |     \-+- 28151 twan /Applications/MATLAB_R2015b.app/bin/maci64/MATLAB -wait -nosplash -nodisplay -r cd('/Users/twan/code/drake/externals/spotless');spot_pods_install('/Users/twan/code/drake/build/matlab','../../externals/spotless');exit -nodesktop
 |       \--= 29460 twan /Applications/MATLAB_R2015b.app/bin/maci64/matlab_helper /dev/ttys003 no
```
So that points in the direction of this matlab call in spotless. Unfortunately I haven't been able to reproduce this reliably.

**Comment by RussTedrake** [comment]
the wait has always generated that warning on non-windows.  it’s necessary on windows.

**Comment by jamiesnape** [comment]
There are two issues here:

1. Removing the `-wait` command for non-Windows builds is easy enough. This would need to be fixed in several places in Drake and its sub-projects.
2. I have seen the leftover MATLAB processes on my Jenkins builds. I have not had a chance to debug this, but  it needs to be fixed since it prevents the Jenkins slave from exiting cleanly.

I would suggest that @tkoolen opens two new tickets for the two issues.

**Comment by RussTedrake** [comment]
i have not tested this, but the -wait used to be only on windows and was 
absolutely required. we need to test before removing it.
